/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package StoreToHeaven;

import java.awt.event.ItemEvent;
import java.io.File;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class WreathDetail extends javax.swing.JPanel {
final JFileChooser fc = new JFileChooser();
private ArrayList<WreathDetail> wdList;
private JPanel jp;
    /**
     * Creates new form WreathDetail
     */
    public WreathDetail(ArrayList l, JPanel jp) {
        wdList = l; 
        this.jp = jp;
        fc.setMultiSelectionEnabled(false);
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        FileLB = new javax.swing.JLabel();
        FileLB1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        FileLB2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        FileLB3 = new javax.swing.JLabel();
        deleteCB = new javax.swing.JCheckBox();

        setBackground(new java.awt.Color(255, 241, 211));
        setLayout(null);

        jButton1.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jButton1.setText("กดแนบรูปภาพ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(10, 10, 106, 26);

        FileLB.setBackground(new java.awt.Color(204, 255, 255));
        FileLB.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        add(FileLB);
        FileLB.setBounds(130, 10, 160, 30);

        FileLB1.setBackground(new java.awt.Color(204, 255, 255));
        FileLB1.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        FileLB1.setText("รายละเอียด ");
        add(FileLB1);
        FileLB1.setBounds(10, 40, 66, 22);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        add(jScrollPane1);
        jScrollPane1.setBounds(10, 70, 347, 101);

        FileLB2.setBackground(new java.awt.Color(204, 255, 255));
        FileLB2.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        FileLB2.setText("ราคา");
        add(FileLB2);
        FileLB2.setBounds(210, 40, 27, 21);
        add(jTextField1);
        jTextField1.setBounds(240, 40, 76, 22);

        FileLB3.setBackground(new java.awt.Color(204, 255, 255));
        FileLB3.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        FileLB3.setText("บาทต่อชิ้น");
        add(FileLB3);
        FileLB3.setBounds(320, 40, 55, 21);

        deleteCB.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        deleteCB.setText("เลือกเพื่อลบ");
        deleteCB.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                deleteCBItemStateChanged(evt);
            }
        });
        deleteCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteCBActionPerformed(evt);
            }
        });
        add(deleteCB);
        deleteCB.setBounds(310, 10, 85, 20);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int returnVal = fc.showDialog(null, "Choose");
        if (returnVal == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            FileLB.setText("รูปภาพที่แนบ: "+file.getName());
            //JOptionPane.showMessageDialog(jButton1, file);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void deleteCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteCBActionPerformed

    private void deleteCBItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_deleteCBItemStateChanged
        // TODO add your handling code here:
//        if (evt.getStateChange() == ItemEvent.SELECTED){
//           wdList.remove(  getPanelIndex());
//        }
    }//GEN-LAST:event_deleteCBItemStateChanged
private int getPanelIndex(){
    return wdList.indexOf(this);
}
// /* testing panel*/
//    public static void main(String[] args){
//        JFrame f = new JFrame();
//        f.setContentPane(new WreathDetail());
//        f.setSize(1200,700);
//        f.setResizable(false);
//        f.setLocationRelativeTo(null);
//        f.setVisible(true);
//        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FileLB;
    private javax.swing.JLabel FileLB1;
    private javax.swing.JLabel FileLB2;
    private javax.swing.JLabel FileLB3;
    private javax.swing.JCheckBox deleteCB;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    public JCheckBox getDeleteCB() {
        return deleteCB;
    }

    public void setDeleteCB(JCheckBox deleteCB) {
        this.deleteCB = deleteCB;
    }
}
