/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import java.awt.CardLayout;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.FileInputStream;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.ClientAnchor;
import org.apache.poi.ss.usermodel.PictureData;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFDrawing;
import org.apache.poi.xssf.usermodel.XSSFPicture;
import org.apache.poi.xssf.usermodel.XSSFShape;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
public class Main_ProductInCart extends javax.swing.JPanel {

    /**
     * Creates new form MainFrame
     */
    public Main_ProductInCart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CartJP = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        menuBar.setBackground(new java.awt.Color(89, 73, 34));
        menuBar.setPreferredSize(new java.awt.Dimension(800, 100));
        menuBar.setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(89, 73, 34));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("ปรับแต่ง");
        jToggleButton1.setBorder(null);
        menuBar.add(jToggleButton1);
        jToggleButton1.setBounds(650, 0, 110, 100);

        jToggleButton2.setBackground(new java.awt.Color(89, 73, 34));
        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("แพ็คเกจ\n");
        jToggleButton2.setBorder(null);
        menuBar.add(jToggleButton2);
        jToggleButton2.setBounds(530, 0, 110, 100);

        jToggleButton3.setBackground(new java.awt.Color(89, 73, 34));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("ผลิตภัณฑ์");
        jToggleButton3.setBorder(null);
        menuBar.add(jToggleButton3);
        jToggleButton3.setBounds(410, 0, 110, 100);

        jToggleButton4.setBackground(new java.awt.Color(89, 73, 34));
        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton4.setText("เกี่ยวกับเรา");
        jToggleButton4.setBorder(null);
        menuBar.add(jToggleButton4);
        jToggleButton4.setBounds(280, 0, 120, 100);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGO");
        menuBar.add(jLabel1);
        jLabel1.setBounds(70, 40, 37, 16);

        jButton1.setText("TEST add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuBar.add(jButton1);
        jButton1.setBounds(160, 40, 110, 23);

        add(menuBar, java.awt.BorderLayout.PAGE_START);

        CartJP.setBackground(new java.awt.Color(204, 204, 255));

        javax.swing.GroupLayout CartJPLayout = new javax.swing.GroupLayout(CartJP);
        CartJP.setLayout(CartJPLayout);
        CartJPLayout.setHorizontalGroup(
            CartJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        CartJPLayout.setVerticalGroup(
            CartJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        CartJP.setLayout(new java.awt.CardLayout());
        ToHeaven.ProductInCart t = new ToHeaven.ProductInCart(CartJP);
        // get InventoryCart as parameter
        CartJP.add(t, "ToHeaven.ProductInCart");
        CartJP.add(new Payment(CartJP),"payment");
        CardLayout cl = (CardLayout) CartJP.getLayout();
        cl.show(CartJP, "Cart_test");

        add(CartJP, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    private BufferedImage getImageFromExcel(String name,int indexsheet) throws Exception{
        FileInputStream fileInput = new FileInputStream("StoreStock.xlsx");
        Workbook wb = new XSSFWorkbook(fileInput);
        Sheet sheet = wb.getSheetAt(indexsheet); // ชีตที่คุณต้องการ

        BufferedImage tmpImg = null;

        // วนลูปตรวจสอบแต่ละแถวใน Sheet
        for (Row row : sheet) {
            Cell firstCell = row.getCell(0); // คอลัมน์แรกที่มีชื่อ
            if (firstCell != null && firstCell.getStringCellValue().equals(name)) {
                System.out.println("Found cell name");
                // ถ้าพบชื่อที่ต้องการ, ตรวจสอบว่ามีรูปภาพในแถวนี้หรือไม่
                XSSFDrawing drawing = (XSSFDrawing) sheet.getDrawingPatriarch();
                if (drawing != null) {
                    System.out.println("drawing pass");
                    for (XSSFShape shape : drawing.getShapes()) {
                        System.out.println("shape pass");
                        if (shape instanceof XSSFPicture) {
                            XSSFPicture picture = (XSSFPicture) shape;
                            ClientAnchor anchor = picture.getPreferredSize();

                            // ตรวจสอบว่าแถวของรูปภาพตรงกับแถวที่เราพบชื่อหรือไม่
                            if (anchor.getRow1() == row.getRowNum()) {
                                PictureData pictureData = picture.getPictureData();
                                byte[] imageBytes = pictureData.getData();

                                // แปลง byte array เป็น BufferedImage
                                ByteArrayInputStream bis = new ByteArrayInputStream(imageBytes);
                                tmpImg = ImageIO.read(bis);
                                bis.close();
                                System.out.println("byte pass");
                                break;
                            }
                        }
                    }
                }
            }
        }

        // ปิดไฟล์ Excel
        wb.close();
        fileInput.close();

        return tmpImg; // คืนค่า BufferedImage ที่ดึงมา
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try{
            String name = "form_9";
            BufferedImage tmpImg = getImageFromExcel(name,6);
            if (tmpImg == null) {
                System.err.println("Image not found for: " + name);
                return; // หยุดการทำงานถ้าภาพไม่ถูกต้อง
            }
            double price= 100;
            int quentity = 3;
            System.out.println("Before new");
            ProductInCart.add(new Picked_product(name,price,quentity,tmpImg));
            System.out.println("added success");
        }catch(Exception e){System.out.println(e);}
    }//GEN-LAST:event_jButton1ActionPerformed
 /* testing panel*/
    public static void main(String[] args){
        JFrame f = new JFrame();
        f.setContentPane(new Main_ProductInCart());
        f.setSize(800,500);
        f.setResizable(false);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartJP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel menuBar;
    // End of variables declaration//GEN-END:variables
}
