/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author LENOVO
 */
public class MainFrame extends javax.swing.JPanel {

    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        frameJP = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        menuBar.setBackground(new java.awt.Color(255, 204, 204));
        menuBar.setPreferredSize(new java.awt.Dimension(800, 100));
        menuBar.setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton1.setFont(new java.awt.Font("MiTNThin", 0, 18)); // NOI18N
        jToggleButton1.setText("ปรับแต่ง");
        jToggleButton1.setBorder(null);
        menuBar.add(jToggleButton1);
        jToggleButton1.setBounds(650, 0, 110, 100);

        jToggleButton2.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton2.setFont(new java.awt.Font("MiTNThin", 0, 18)); // NOI18N
        jToggleButton2.setText("แพ็คเกจ\n");
        jToggleButton2.setBorder(null);
        menuBar.add(jToggleButton2);
        jToggleButton2.setBounds(530, 0, 110, 100);

        jToggleButton3.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton3.setFont(new java.awt.Font("MiTNThin", 0, 18)); // NOI18N
        jToggleButton3.setText("ผลิตภัณฑ์");
        jToggleButton3.setBorder(null);
        menuBar.add(jToggleButton3);
        jToggleButton3.setBounds(410, 0, 110, 100);

        jToggleButton4.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton4.setFont(new java.awt.Font("MiTNThin", 0, 18)); // NOI18N
        jToggleButton4.setText("เกี่ยวกับเรา");
        jToggleButton4.setBorder(null);
        menuBar.add(jToggleButton4);
        jToggleButton4.setBounds(280, 0, 120, 100);

        jLabel1.setText("LOGO");
        menuBar.add(jLabel1);
        jLabel1.setBounds(70, 40, 37, 16);

        add(menuBar, java.awt.BorderLayout.PAGE_START);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        frameJP.setBackground(new java.awt.Color(204, 255, 102));
        ProductPage pp = new ProductPage(frameJP);
        frameJP.add(pp,"propage");
        CardLayout cd =(CardLayout)frameJP.getLayout();
        cd.show(frameJP,"propage");

        javax.swing.GroupLayout frameJPLayout = new javax.swing.GroupLayout(frameJP);
        frameJP.setLayout(frameJPLayout);
        frameJPLayout.setHorizontalGroup(
            frameJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 945, Short.MAX_VALUE)
        );
        frameJPLayout.setVerticalGroup(
            frameJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 879, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(frameJP);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
 /* testing panel*/
    public static void main(String[] args){
        JFrame f = new JFrame();
        f.setContentPane(new MainFrame());
        f.setSize(800,500);
        f.setResizable(false);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel frameJP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel menuBar;
    // End of variables declaration//GEN-END:variables
}
