/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import java.awt.CardLayout;
import javax.swing.JFrame;
import java.util.*;
public class Main_ProductInCart extends javax.swing.JPanel {

    /**
     * Creates new form MainFrame
     */
    public Main_ProductInCart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton4 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        CartJP = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        menuBar.setBackground(new java.awt.Color(219, 237, 255));
        menuBar.setPreferredSize(new java.awt.Dimension(800, 100));
        menuBar.setLayout(null);

        jToggleButton1.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("ปรับแต่ง");
        jToggleButton1.setBorder(null);
        menuBar.add(jToggleButton1);
        jToggleButton1.setBounds(650, 0, 110, 100);

        jToggleButton2.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton2.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton2.setText("แพ็คเกจ\n");
        jToggleButton2.setBorder(null);
        menuBar.add(jToggleButton2);
        jToggleButton2.setBounds(530, 0, 110, 100);

        jToggleButton3.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton3.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton3.setText("ผลิตภัณฑ์");
        jToggleButton3.setBorder(null);
        menuBar.add(jToggleButton3);
        jToggleButton3.setBounds(410, 0, 110, 100);

        jToggleButton4.setBackground(new java.awt.Color(255, 204, 204));
        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton4.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton4.setText("เกี่ยวกับเรา");
        jToggleButton4.setBorder(null);
        menuBar.add(jToggleButton4);
        jToggleButton4.setBounds(280, 0, 120, 100);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGO");
        menuBar.add(jLabel1);
        jLabel1.setBounds(70, 40, 37, 16);

        jButton1.setFont(new java.awt.Font("TH Sarabun New", 0, 18)); // NOI18N
        jButton1.setText("เพิ่มสินค้า");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        menuBar.add(jButton1);
        jButton1.setBounds(160, 40, 110, 32);

        add(menuBar, java.awt.BorderLayout.PAGE_START);

        CartJP.setBackground(new java.awt.Color(189, 189, 255));

        javax.swing.GroupLayout CartJPLayout = new javax.swing.GroupLayout(CartJP);
        CartJP.setLayout(CartJPLayout);
        CartJPLayout.setHorizontalGroup(
            CartJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        CartJPLayout.setVerticalGroup(
            CartJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );

        CartJP.setLayout(new java.awt.CardLayout());
        ToHeaven.ProductInCart t = new ToHeaven.ProductInCart(CartJP);
        // get InventoryCart as parameter
        CartJP.add(t, "ToHeaven.ProductInCart");
        CartJP.add(new Payment(CartJP),"payment");
        CardLayout cl = (CardLayout) CartJP.getLayout();
        cl.show(CartJP, "Cart_test");

        add(CartJP, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ProductInCart.add(new Picked_product("test",100*Math.random(),(int)(10*Math.random()),"/ToHeaven/t.png"));
    }//GEN-LAST:event_jButton1ActionPerformed
 /* testing panel*/
    public static void main(String[] args){
        JFrame f = new JFrame();
        f.setContentPane(new Main_ProductInCart());
        f.setSize(800,500);
        f.setResizable(false);
        f.setLocationRelativeTo(null);
        f.setVisible(true);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CartJP;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JPanel menuBar;
    // End of variables declaration//GEN-END:variables
}
