/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import DAO.*;
import StoreToHeaven.*;
import java.util.*;
import javax.swing.ImageIcon;
//import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JRadioButton;

/**
 *
 * @author ASUS
 */
public class PackageProduct extends javax.swing.JPanel {
    private ArrayList<Package_Class> pkList;
    private Package_Class packageClass;
    
    public PackageProduct(Package_Class pack) {
        initComponents();
        getData(pack);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupWreath = new javax.swing.ButtonGroup();
        groupColors = new javax.swing.ButtonGroup();
        choosePieceWreath = new javax.swing.JLabel();
        pieceWreath = new javax.swing.JSpinner();
        productImage = new javax.swing.JLabel();
        scrollDetail = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();
        message = new javax.swing.JLabel();
        textMessage = new javax.swing.JTextField();
        name = new javax.swing.JLabel();
        priceLB = new javax.swing.JLabel();

        setBackground(new java.awt.Color(244, 244, 224));
        setPreferredSize(new java.awt.Dimension(780, 400));
        setLayout(null);

        choosePieceWreath.setFont(new java.awt.Font("TH Sarabun New", 1, 22)); // NOI18N
        choosePieceWreath.setText("ระบุจำนวนสินค้า");
        add(choosePieceWreath);
        choosePieceWreath.setBounds(490, 280, 120, 33);

        pieceWreath.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(pieceWreath);
        pieceWreath.setBounds(610, 280, 80, 30);

        productImage.setPreferredSize(new java.awt.Dimension(180, 180));
        add(productImage);
        productImage.setBounds(70, 40, 180, 180);

        scrollDetail.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollDetail.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        details.setEditable(false);
        details.setColumns(20);
        details.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        details.setRows(5);
        scrollDetail.setViewportView(details);

        add(scrollDetail);
        scrollDetail.setBounds(330, 50, 410, 180);

        message.setFont(new java.awt.Font("TH Sarabun New", 1, 22)); // NOI18N
        message.setText("กรุณาระบุข้อความ");
        add(message);
        message.setBounds(50, 250, 219, 30);
        add(textMessage);
        textMessage.setBounds(50, 280, 330, 45);

        name.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        add(name);
        name.setBounds(40, 20, 270, 31);

        priceLB.setFont(new java.awt.Font("TH SarabunPSK", 0, 24)); // NOI18N
        priceLB.setText("ราคา : ");
        add(priceLB);
        priceLB.setBounds(330, 20, 280, 30);
    }// </editor-fold>//GEN-END:initComponents

    public void getData(Package_Class pack){
        this.packageClass = pack;
        name.setText(packageClass.toString());
        details.setText(packageClass.getDetail());
        productImage.setIcon(new ImageIcon(packageClass.getPath()));
        priceLB.setText(packageClass.getPrice()+"บาท");
    }

    public Package_Class getPackageClass() {
        return packageClass;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel choosePieceWreath;
    private javax.swing.JTextArea details;
    private javax.swing.ButtonGroup groupColors;
    private javax.swing.ButtonGroup groupWreath;
    private javax.swing.JLabel message;
    private javax.swing.JLabel name;
    private javax.swing.JSpinner pieceWreath;
    private javax.swing.JLabel priceLB;
    private javax.swing.JLabel productImage;
    private javax.swing.JScrollPane scrollDetail;
    private javax.swing.JTextField textMessage;
    // End of variables declaration//GEN-END:variables
}
