/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Chotika
 */
public class ProductInCart extends javax.swing.JPanel {

    private CardLayout cd;
    private JPanel Main_panel;
    /**
     * Creates new form ProductInCart
     */
    public ProductInCart(JPanel mainPanel) {
        this.Main_panel = mainPanel;
        cd = (CardLayout) mainPanel.getLayout();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HeaderJP = new javax.swing.JPanel();
        header_textJL = new javax.swing.JLabel();
        PaybarJP = new javax.swing.JPanel();
        PayButton_JP = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Scroll_page = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 204, 153));
        setPreferredSize(new java.awt.Dimension(800, 500));
        setLayout(new java.awt.BorderLayout());

        HeaderJP.setBackground(new java.awt.Color(89, 73, 34));
        HeaderJP.setPreferredSize(new java.awt.Dimension(800, 52));

        header_textJL.setBackground(new java.awt.Color(0, 0, 0));
        header_textJL.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        header_textJL.setForeground(new java.awt.Color(255, 255, 255));
        header_textJL.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        header_textJL.setText("สินค้าในตะกร้า");

        javax.swing.GroupLayout HeaderJPLayout = new javax.swing.GroupLayout(HeaderJP);
        HeaderJP.setLayout(HeaderJPLayout);
        HeaderJPLayout.setHorizontalGroup(
            HeaderJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderJPLayout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addComponent(header_textJL, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
        HeaderJPLayout.setVerticalGroup(
            HeaderJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HeaderJPLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(header_textJL, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(HeaderJP, java.awt.BorderLayout.PAGE_START);

        PaybarJP.setBackground(new java.awt.Color(215, 186, 143));
        PaybarJP.setPreferredSize(new java.awt.Dimension(800, 45));

        PayButton_JP.setBackground(new java.awt.Color(196, 166, 121));
        PayButton_JP.setPreferredSize(new java.awt.Dimension(100, 52));
        PayButton_JP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PayButton_JPMouseClicked(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(204, 204, 204));
        jLabel2.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ชำระเงิน>");

        javax.swing.GroupLayout PayButton_JPLayout = new javax.swing.GroupLayout(PayButton_JP);
        PayButton_JP.setLayout(PayButton_JPLayout);
        PayButton_JPLayout.setHorizontalGroup(
            PayButton_JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PayButton_JPLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        PayButton_JPLayout.setVerticalGroup(
            PayButton_JPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PayButton_JPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout PaybarJPLayout = new javax.swing.GroupLayout(PaybarJP);
        PaybarJP.setLayout(PaybarJPLayout);
        PaybarJPLayout.setHorizontalGroup(
            PaybarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PaybarJPLayout.createSequentialGroup()
                .addGap(0, 712, Short.MAX_VALUE)
                .addComponent(PayButton_JP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PaybarJPLayout.setVerticalGroup(
            PaybarJPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PayButton_JP, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
        );

        add(PaybarJP, java.awt.BorderLayout.PAGE_END);

        jScrollPane2.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane2.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        Scroll_page.setBackground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout Scroll_pageLayout = new javax.swing.GroupLayout(Scroll_page);
        Scroll_page.setLayout(Scroll_pageLayout);
        Scroll_pageLayout.setHorizontalGroup(
            Scroll_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        Scroll_pageLayout.setVerticalGroup(
            Scroll_pageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        Scroll_page.setLayout(new java.awt.GridLayout(0, 1));
        //addtest.add(new Picked_product(), Scroll_page);
        Scroll_page.add(new ToHeaven.Picked_product());
        //Scroll_page.revalidate();
        //Scroll_page.repaint();
        Scroll_page.setPreferredSize(new java.awt.Dimension(800, 600));
        Scroll_page.add(new ToHeaven.Picked_product());
        Scroll_page.setPreferredSize(new java.awt.Dimension(800, 900));
        Scroll_page.add(new ToHeaven.Picked_product());

        jScrollPane2.setViewportView(Scroll_page);

        add(jScrollPane2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void PayButton_JPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PayButton_JPMouseClicked
        
    }//GEN-LAST:event_PayButton_JPMouseClicked
//public static void main(String[] args){
//    JFrame f = new JFrame();
//    f.setContentPane(new ProductInCart());
//    f.setLocationRelativeTo(null);
//    f.setSize(800,1200);
//    f.setVisible(true);
//    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel HeaderJP;
    private javax.swing.JPanel PayButton_JP;
    private javax.swing.JPanel PaybarJP;
    private javax.swing.JPanel Scroll_page;
    private javax.swing.JLabel header_textJL;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
