/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */
public class ProductPage extends javax.swing.JPanel {
    private CardLayout cd;
    private JPanel mainPanel;
    
    public ProductPage(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        cd = (CardLayout) mainPanel.getLayout();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        product = new javax.swing.JLabel();
        wreath = new javax.swing.JLabel();
        snackBox = new javax.swing.JLabel();
        pictureFrame = new javax.swing.JLabel();
        souvenir = new javax.swing.JLabel();
        incenseStick = new javax.swing.JLabel();
        offering = new javax.swing.JLabel();
        coffin = new javax.swing.JLabel();
        sandalWood = new javax.swing.JLabel();
        candle = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 217, 220));
        setMaximumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(800, 400));

        product.setFont(new java.awt.Font("TH Sarabun New", 1, 36)); // NOI18N
        product.setText("ผลิตภัณฑ์");

        wreath.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        wreath.setText("พวงหรีด");
        wreath.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                wreathMouseClicked(evt);
            }
        });

        snackBox.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        snackBox.setText("ชุดอาหารว่าง");

        pictureFrame.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        pictureFrame.setText("กรอบรูป");

        souvenir.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        souvenir.setText("ของชำร่วย");

        incenseStick.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        incenseStick.setText("ธูป");

        offering.setFont(new java.awt.Font("TH SarabunPSK", 1, 24)); // NOI18N
        offering.setText("เครื่องไทยธรรม");

        coffin.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        coffin.setText("โลงศพ");

        sandalWood.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        sandalWood.setText("ดอกไม้จันทน์");

        candle.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        candle.setText("เทียน");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(wreath, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pictureFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(snackBox, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sandalWood))
                        .addGap(167, 167, 167)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(coffin, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(incenseStick, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(souvenir, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(candle)
                            .addComponent(offering, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 193, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(product, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(souvenir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(wreath, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(snackBox, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(incenseStick))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pictureFrame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(candle))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sandalWood)
                    .addComponent(coffin, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addComponent(offering, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void wreathMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_wreathMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_wreathMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel candle;
    private javax.swing.JLabel coffin;
    private javax.swing.JLabel incenseStick;
    private javax.swing.JLabel offering;
    private javax.swing.JLabel pictureFrame;
    private javax.swing.JLabel product;
    private javax.swing.JLabel sandalWood;
    private javax.swing.JLabel snackBox;
    private javax.swing.JLabel souvenir;
    private javax.swing.JLabel wreath;
    // End of variables declaration//GEN-END:variables
}
