/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import java.io.File;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JPanel;

/**
 *
 * @author ASUS
 */



public class ProductFrame extends javax.swing.JPanel {
    final JFileChooser fc = new JFileChooser();
    private ArrayList<ProductFrame> pfList;
    private JPanel jp;
    /**
     * Creates new form ProductFrame
     */
    public ProductFrame(ArrayList l, JPanel jp) {
        pfList = l; 
        this.jp = jp;
        fc.setMultiSelectionEnabled(false);
        fc.setCurrentDirectory(new File(System.getProperty("user.home")));
        initComponents();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chooseImage = new javax.swing.JLabel();
        pressForChoose = new javax.swing.JButton();
        productImage = new javax.swing.JLabel();
        detailOfProduct = new javax.swing.JScrollPane();
        detailProduct = new javax.swing.JTextArea();
        pieceFrame = new javax.swing.JSpinner();
        price = new javax.swing.JLabel();
        showPicName = new javax.swing.JLabel();
        ChoosePieceFrame = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 340));
        setLayout(null);

        chooseImage.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        chooseImage.setText("กรุณาเลือกรูปภาพ");
        add(chooseImage);
        chooseImage.setBounds(46, 213, 136, 33);

        pressForChoose.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        pressForChoose.setText("กดแนบรูปภาพ");
        pressForChoose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pressForChooseActionPerformed(evt);
            }
        });
        add(pressForChoose);
        pressForChoose.setBounds(46, 264, 122, 34);

        productImage.setPreferredSize(new java.awt.Dimension(180, 180));
        add(productImage);
        productImage.setBounds(20, 25, 180, 180);

        detailProduct.setEditable(false);
        detailProduct.setColumns(20);
        detailProduct.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        detailProduct.setRows(5);
        detailProduct.setPreferredSize(new java.awt.Dimension(330, 140));
        detailOfProduct.setViewportView(detailProduct);

        add(detailOfProduct);
        detailOfProduct.setBounds(241, 25, 332, 144);

        pieceFrame.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        add(pieceFrame);
        pieceFrame.setBounds(46, 367, 64, 22);
        add(price);
        price.setBounds(367, 187, 80, 20);

        showPicName.setBackground(new java.awt.Color(204, 255, 255));
        showPicName.setFont(new java.awt.Font("TH SarabunPSK", 1, 18)); // NOI18N
        add(showPicName);
        showPicName.setBounds(184, 264, 160, 30);

        ChoosePieceFrame.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        ChoosePieceFrame.setText("กรุณาเลือกจำนวนสินค้า");
        add(ChoosePieceFrame);
        ChoosePieceFrame.setBounds(46, 316, 172, 33);
    }// </editor-fold>//GEN-END:initComponents

    private void pressForChooseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pressForChooseActionPerformed
                                    
        // TODO add your handling code here:
        int returnVal = fc.showDialog(null, "Choose");
        if (returnVal == JFileChooser.APPROVE_OPTION){
            File file = fc.getSelectedFile();
            showPicName.setText("รูปภาพที่แนบ: "+file.getName());
            //JOptionPane.showMessageDialog(jButton1, file);
        }
    
    }//GEN-LAST:event_pressForChooseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ChoosePieceFrame;
    private javax.swing.JLabel chooseImage;
    private javax.swing.JScrollPane detailOfProduct;
    private javax.swing.JTextArea detailProduct;
    private javax.swing.JSpinner pieceFrame;
    private javax.swing.JButton pressForChoose;
    private javax.swing.JLabel price;
    private javax.swing.JLabel productImage;
    private javax.swing.JLabel showPicName;
    // End of variables declaration//GEN-END:variables
}
