/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import javax.swing.JFrame;
import javax.swing.JRadioButton;

/**
 *
 * @author ASUS
 */
public class ProductWreathAndSandalWood extends javax.swing.JPanel {

    /**
     * Creates new form ProductWreath
     */
    public ProductWreathAndSandalWood() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        groupWreath = new javax.swing.ButtonGroup();
        groupColors = new javax.swing.ButtonGroup();
        silk = new javax.swing.JRadioButton();
        artiflower = new javax.swing.JRadioButton();
        pink = new javax.swing.JRadioButton();
        green = new javax.swing.JRadioButton();
        purple = new javax.swing.JRadioButton();
        orange = new javax.swing.JRadioButton();
        rainbow = new javax.swing.JRadioButton();
        choose = new javax.swing.JLabel();
        chooseColor = new javax.swing.JLabel();
        choosePieceWreath = new javax.swing.JLabel();
        pieceWreath = new javax.swing.JSpinner();
        productImage = new javax.swing.JLabel();
        scrollDetail = new javax.swing.JScrollPane();
        details = new javax.swing.JTextArea();
        message = new javax.swing.JLabel();
        textMessage = new javax.swing.JTextField();
        price = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 217, 220));
        setPreferredSize(new java.awt.Dimension(600, 750));

        groupWreath.add(silk);
        silk.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        silk.setText("พวงหรีดผ้า");

        groupWreath.add(artiflower);
        artiflower.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        artiflower.setText("พวงหรีดดอกไม้ปลอม");

        groupColors.add(pink);
        pink.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        pink.setText("สีชมพู");

        groupColors.add(green);
        green.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        green.setText("สีเขียว");
        green.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greenActionPerformed(evt);
            }
        });

        groupColors.add(purple);
        purple.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        purple.setText("สีม่วง");

        groupColors.add(orange);
        orange.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        orange.setText("สีส้ม");

        groupColors.add(rainbow);
        rainbow.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        rainbow.setText("หลากสี");

        choose.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        choose.setText("กรุณาเลือกชนิดพวงหรีด");

        chooseColor.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        chooseColor.setText("กรุณาเลือกสีพวงหรีด");

        choosePieceWreath.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        choosePieceWreath.setText("กรุณาเลือกจำนวนสินค้า");

        pieceWreath.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        productImage.setPreferredSize(new java.awt.Dimension(180, 180));

        details.setEditable(false);
        details.setColumns(20);
        details.setFont(new java.awt.Font("TH SarabunPSK", 0, 18)); // NOI18N
        details.setRows(5);
        scrollDetail.setViewportView(details);

        message.setFont(new java.awt.Font("TH Sarabun New", 1, 24)); // NOI18N
        message.setText("กรุณาระบุข้อความบนพวงหรีด");

        price.setFont(new java.awt.Font("TH Sarabun New", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pieceWreath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(choosePieceWreath)
                            .addComponent(chooseColor)
                            .addComponent(choose)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(200, 200, 200)
                                .addComponent(scrollDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(artiflower, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(silk, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pink)
                                .addGap(18, 18, 18)
                                .addComponent(green)
                                .addGap(18, 18, 18)
                                .addComponent(purple)
                                .addGap(18, 18, 18)
                                .addComponent(orange)
                                .addGap(18, 18, 18)
                                .addComponent(rainbow)))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(message)
                            .addComponent(textMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(productImage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(choose))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(price, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(artiflower, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silk))
                .addGap(18, 18, 18)
                .addComponent(chooseColor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pink)
                    .addComponent(green)
                    .addComponent(purple)
                    .addComponent(orange)
                    .addComponent(rainbow))
                .addGap(18, 18, 18)
                .addComponent(message)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textMessage, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(choosePieceWreath)
                .addGap(18, 18, 18)
                .addComponent(pieceWreath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void greenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_greenActionPerformed
public static void main(String[] args){
    JFrame f = new JFrame();
    f.setContentPane(new ProductWreathAndSandalWood());
    f.setSize(600, 750);
    f.setVisible(true);
    f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton artiflower;
    private javax.swing.JLabel choose;
    private javax.swing.JLabel chooseColor;
    private javax.swing.JLabel choosePieceWreath;
    private javax.swing.JTextArea details;
    private javax.swing.JRadioButton green;
    private javax.swing.ButtonGroup groupColors;
    private javax.swing.ButtonGroup groupWreath;
    private javax.swing.JLabel message;
    private javax.swing.JRadioButton orange;
    private javax.swing.JSpinner pieceWreath;
    private javax.swing.JRadioButton pink;
    private javax.swing.JLabel price;
    private javax.swing.JLabel productImage;
    private javax.swing.JRadioButton purple;
    private javax.swing.JRadioButton rainbow;
    private javax.swing.JScrollPane scrollDetail;
    private javax.swing.JRadioButton silk;
    private javax.swing.JTextField textMessage;
    // End of variables declaration//GEN-END:variables
}
