/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ToHeaven;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.*;

/**
 *
 * @author LENOVO
 */
public class regist extends javax.swing.JPanel {
//CardLayout card ;
    JFrame f ;
     private JPanel mainPanel;
     CardLayout cardLayout;
    /**
     * Creates new form regist
     */
    public regist() {
        initComponents();
//         f = new JFrame();
//        f.setLayout(new CardLayout());
//        f.setContentPane(this);
//        
//        card= (CardLayout) f.getContentPane().getLayout();
//        f.getContentPane().add(new home(), "home");
//        f.setSize(500, 500);  // กำหนดขนาดของ JFrame
//
//        f.setVisible(true); 
//card = (CardLayout) this.getLayout();
//f = new JFrame();  // สร้าง JFrame
//        card = new CardLayout();  // กำหนดให้ใช้ CardLayout
//        this.setLayout(card);  // กำหนด layout ของ JPanel นี้เป็น CardLayout
//        f.setContentPane(this);  // กำหนด JPanel (this) ให้เป็น content pane ของ JFrame
//        this.add(new home(), "home");  // เพิ่ม login panel ใน card layout
//
//        f.setSize(500, 500);  // กำหนดขนาดของ JFrame
//        f.setVisible(true);  // แสดง JFrame
    }
     public regist(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        cardLayout = (CardLayout) mainPanel.getLayout();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 255));
        setLayout(new java.awt.CardLayout());

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jLabel1.setText("REGIST");

        jButton1.setText("confirm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(151, 151, 151)
                        .addComponent(jButton1)))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 220, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(45, 45, 45))
        );

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
//        card.show(f.getContentPane(), "home");
// card.show(this, "home");
//CardLayout cardLayout = (CardLayout) mainPanel.getLayout();
        cardLayout.show(mainPanel, "home");
 
        
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
